### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by thmohd** [ruflin/Elastica.io#31]
I am new to Eelasticsearch, My question is why should I use Elastica.io if Elasticsearch offer PHP API ?

**Comment by ruflin** [comment]
@thmohd The Elastica PHP client existed before elasticsearch created there own one. The clients are quite different. Elastica represents everything as objects and builds the queries, filters etc. for you. If you compare it to MySQL, you could ask if you should use the mysql client directly or use something like Doctrine? The comparison does not work to 100% but goes in the right direction. Both has its pros and cons and depends in the end on what you need it for.
